# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: seaproject
service: sea-project-backend

provider:
  name: aws
  runtime: python3.10
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true

functions:
  api:
    handler: app.main.handler
    architecture: arm64
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

package:
  patterns:
    - '!**/*.pyc'
    - '!.env/**'
    - '!node_modules/**'

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    layer: true
    pythonBin: python3
    architectures:
      - arm64
