service: sea-project-backend

provider:
  name: aws
  runtime: python3.10
  region: eu-west-2
  stage: ${opt:stage, 'dev'}

functions:
  api:
    handler: app.main.handler
    architecture: arm64
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  patterns:
    - '!**/*.pyc'
    - '!.env/**'
    - '!node_modules/**'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
    pythonBin: python3
    architectures:
      - arm64
