service: sea-project-backend

provider:
  name: aws
  runtime: python3.10
  region: eu-west-2
  stage: ${opt:stage, 'dev'}

functions:
  api:
    handler: app.main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  patterns:
    - '!**/*.pyc'
    - '!.env/**'
    - '!node_modules/**'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: python-deps
      description: Python dependencies for API
