# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: seaproject
service: sea-project-backend
frameworkVersion: '4'

provider:
  name: aws
  profile: tipub-Admin
  runtime: python3.9
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true

functions:
  api:
    handler: app.main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: "*"

package:
  patterns:
    - "!**/*.pyc"
    - "!.env/**"
    - "!node_modules/**"

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-stack-output

custom:
  output:
    - handler: scripts/output.handler # Run the handler in this file
      file: scripts/dist/config.json # toml, yaml, yml, and json format is available. Make sure the location where you want to save the file exists
